language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
before_deploy:
  - node_modules/.bin/json -E "this.version='$TRAVIS_TAG'" -f package.json -I
deploy:
  provider: npm
  email: JanS@DracoBlue.de
  api_key:
    secure: OmCkCTv3LnSjNiIfGLyIQ5ovfuR1h7wvTWlrHMRn1K2ijN/BJEvxiWLwiFmz5MD6ELp6MKziaUrkLQECMR2aGZGQMDQ+/N7stsHk1s5zRQ9WypTyp6gM3smzqbyvvlN1AjH36VuQkSxOP7cocO0OudsR14nAdTB2REHI59ei4bkyr78SQhhCKuyJRUbh4xp3r1HI6wKfB0ibsjvIsyALgIlOQsyP1TR36e0pp2gFejMEwjTg2F2h4LblVBNQyS1CVtf3rOBFe+/s/DffmL0kPOu+op7Oavd4fUeltnY5SShDtrVktKd74YCToHZtX4cMYYth59zXb5aX4wcDdVqNjmI2cfQvVvMA3+c5EuO8eUUYEWS1DY9ud0ujbJejx4dSCZIg6ehwBmSmIFc0uQrsmIrQcT66OcbZgIYa6OrmXwaTWTcQddWZjOIdDJ30OOtcg9f1TJL1HB+C5ZXPzoDWnXkEGNILWz/S+YjDxYmdi3Qt+EmyCnalPKyDKQ1u3LOvTT854GZGEWjTr+9u9XKlXqtZW1vxwEDEJmDlozRzQBs92S5p6qDYY3opCbzwWdNPQlzUFxld0wAlYqLBqtEOtP0+LoFQUEG4F0dnSlLkDQTJZolUd8Tc/MeB8rlX0pp2DlbBUbe2vppkA8HSjA+/ciD9z0IN59PMYuQGsLzM/AA=
  on:
    tags: true
    repo: DracoBlue/cnd-parser
    branch: master
    node: 0.12
